package io.cloudtrailsqs.event.cloudtrail;

import io.cloudtrailsqs.event.util.AlertConfHostBitConstant;

import java.util.Arrays;
import java.util.Optional;

public enum EventNameEnum {
    // EC2
    START_INSTANCES(AlertConfHostBitConstant.ACI_CREATE, "EC2", "StartInstances"),
    STOP_INSTANCES(AlertConfHostBitConstant.ACI_DELETE, "EC2", "StopInstances"),

    CREATE_CreateCapacityReservation(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateCapacityReservation"),
    CREATE_RunInstances(AlertConfHostBitConstant.ACI_CREATE, "EC2", "RunInstances"),
    CREATE_CreateCapacityReservationFleet(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateCapacityReservationFleet"),
    CREATE_CreateCarrierGateway(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateCarrierGateway"),
    CREATE_CreateClientVpnEndpoint(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateClientVpnEndpoint"),
    CREATE_CreateClientVpnRoute(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateClientVpnRoute"),
    CREATE_CreateCoipCidr(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateCoipCidr"),
    CREATE_CreateCoipPool(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateCoipPool"),
    CREATE_CreateCustomerGateway(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateCustomerGateway"),
    CREATE_CreateDefaultSubnet(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateDefaultSubnet"),
    CREATE_CreateDefaultVpc(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateDefaultVpc"),
    CREATE_CreateDhcpOptions(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateDhcpOptions"),
    CREATE_CreateEgressOnlyInternetGateway(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateEgressOnlyInternetGateway"),
    CREATE_CreateFleet(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateFleet"),
    CREATE_CreateFlowLogs(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateFlowLogs"),
    CREATE_CreateFpgaImage(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateFpgaImage"),
    CREATE_CreateImage(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateImage"),
    CREATE_CreateInstanceEventWindow(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateInstanceEventWindow"),
    CREATE_CreateInstanceExportTask(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateInstanceExportTask"),
    CREATE_CreateInternetGateway(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateInternetGateway"),
    CREATE_CreateIpam(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateIpam"),
    CREATE_CreateIpamPool(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateIpamPool"),
    CREATE_CreateIpamScope(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateIpamScope"),
    CREATE_CreateKeyPair(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateKeyPair"),
    CREATE_CreateLaunchTemplate(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateLaunchTemplate"),
    CREATE_CreateLaunchTemplateVersion(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateLaunchTemplateVersion"),
    CREATE_CreateLocalGatewayRoute(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateLocalGatewayRoute"),
    CREATE_CreateLocalGatewayRouteTable(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateLocalGatewayRouteTable"),
    CREATE_CreateLocalGatewayRouteTableVirtualInterfaceGroupAssociation(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateLocalGatewayRouteTableVirtualInterfaceGroupAssociation"),
    CREATE_CreateLocalGatewayRouteTableVpcAssociation(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateLocalGatewayRouteTableVpcAssociation"),
    CREATE_CreateManagedPrefixList(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateManagedPrefixList"),
    CREATE_CreateNatGateway(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateNatGateway"),
    CREATE_CreateNetworkInsightsAccessScope(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateNetworkInsightsAccessScope"),
    CREATE_CreateNetworkInsightsPath(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateNetworkInsightsPath"),
    CREATE_CreateNetworkInterface(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateNetworkInterface"),
    CREATE_CreateNetworkInterfacePermission(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateNetworkInterfacePermission"),
    CREATE_CreatePlacementGroup(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreatePlacementGroup"),
    CREATE_CreatePublicIpv4Pool(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreatePublicIpv4Pool"),
    CREATE_CreateReplaceRootVolumeTask(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateReplaceRootVolumeTask"),
    CREATE_CreateReservedInstancesListing(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateReservedInstancesListing"),
    CREATE_CreateRestoreImageTask(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateRestoreImageTask"),
    CREATE_CreateRoute(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateRoute"),
    CREATE_CreateRouteTable(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateRouteTable"),
    CREATE_CreateSnapshot(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateSnapshot"),
    CREATE_CreateSnapshots(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateSnapshots"),
    CREATE_CreateSpotDatafeedSubscription(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateSpotDatafeedSubscription"),
    CREATE_CreateStoreImageTask(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateStoreImageTask"),
    CREATE_CreateSubnet(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateSubnet"),
    CREATE_CreateSubnetCidrReservation(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateSubnetCidrReservation"),
    CREATE_CreateTags(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTags"),
    CREATE_CreateTrafficMirrorFilter(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTrafficMirrorFilter"),
    CREATE_CreateTrafficMirrorFilterRule(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTrafficMirrorFilterRule"),
    CREATE_CreateTrafficMirrorSession(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTrafficMirrorSession"),
    CREATE_CreateTrafficMirrorTarget(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTrafficMirrorTarget"),
    CREATE_CreateTransitGateway(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGateway"),
    CREATE_CreateTransitGatewayConnect(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayConnect"),
    CREATE_CreateTransitGatewayConnectPeer(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayConnectPeer"),
    CREATE_CreateTransitGatewayMulticastDomain(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayMulticastDomain"),
    CREATE_CreateTransitGatewayPeeringAttachment(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayPeeringAttachment"),
    CREATE_CreateTransitGatewayPolicyTable(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayPolicyTable"),
    CREATE_CreateTransitGatewayPrefixListReference(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayPrefixListReference"),
    CREATE_CreateTransitGatewayRoute(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayRoute"),
    CREATE_CreateTransitGatewayRouteTable(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayRouteTable"),
    CREATE_CreateTransitGatewayRouteTableAnnouncement(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayRouteTableAnnouncement"),
    CREATE_CreateTransitGatewayVpcAttachment(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateTransitGatewayVpcAttachment"),
    CREATE_CreateVolume(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVolume"),
    CREATE_CreateVpc(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVpc"),
    CREATE_CreateVpcEndpoint(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVpcEndpoint"),
    CREATE_CreateVpcEndpointConnectionNotification(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVpcEndpointConnectionNotification"),
    CREATE_CreateVpcEndpointServiceConfiguration(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVpcEndpointServiceConfiguration"),
    CREATE_CreateVpcPeeringConnection(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVpcPeeringConnection"),
    CREATE_CreateVpnConnection(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVpnConnection"),
    CREATE_CreateVpnConnectionRoute(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVpnConnectionRoute"),
    CREATE_CreateVpnGateway(AlertConfHostBitConstant.ACI_CREATE, "EC2", "CreateVpnGateway"),

    MODIFY_ModifyAddressAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyAddressAttribute"),
    MODIFY_ModifyAvailabilityZoneGroup(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyAvailabilityZoneGroup"),
    MODIFY_ModifyCapacityReservation(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyCapacityReservation"),
    MODIFY_ModifyCapacityReservationFleet(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyCapacityReservationFleet"),
    MODIFY_ModifyClientVpnEndpoint(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyClientVpnEndpoint"),
    MODIFY_ModifyDefaultCreditSpecification(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyDefaultCreditSpecification"),
    MODIFY_ModifyEbsDefaultKmsKeyId(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyEbsDefaultKmsKeyId"),
    MODIFY_ModifyFleet(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyFleet"),
    MODIFY_ModifyFpgaImageAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyFpgaImageAttribute"),
    MODIFY_ModifyHosts(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyHosts"),
    MODIFY_ModifyIdentityIdFormat(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyIdentityIdFormat"),
    MODIFY_ModifyIdFormat(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyIdFormat"),
    MODIFY_ModifyImageAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyImageAttribute"),
    MODIFY_ModifyInstanceAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyInstanceAttribute"),
    MODIFY_ModifyInstanceCapacityReservationAttributes(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyInstanceCapacityReservationAttributes"),
    MODIFY_ModifyInstanceCreditSpecification(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyInstanceCreditSpecification"),
    MODIFY_ModifyInstanceEventStartTime(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyInstanceEventStartTime"),
    MODIFY_ModifyInstanceEventWindow(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyInstanceEventWindow"),
    MODIFY_ModifyInstanceMaintenanceOptions(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyInstanceMaintenanceOptions"),
    MODIFY_ModifyInstanceMetadataOptions(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyInstanceMetadataOptions"),
    MODIFY_ModifyInstancePlacement(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyInstancePlacement"),
    MODIFY_ModifyIpam(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyIpam"),
    MODIFY_ModifyIpamPool(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyIpamPool"),
    MODIFY_ModifyIpamResourceCidr(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyIpamResourceCidr"),
    MODIFY_ModifyIpamScope(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyIpamScope"),
    MODIFY_ModifyLaunchTemplate(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyLaunchTemplate"),
    MODIFY_ModifyLocalGatewayRoute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyLocalGatewayRoute"),
    MODIFY_ModifyManagedPrefixList(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyManagedPrefixList"),
    MODIFY_ModifyNetworkInterfaceAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyNetworkInterfaceAttribute"),
    MODIFY_ModifyPrivateDnsNameOptions(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyPrivateDnsNameOptions"),
    MODIFY_ModifyReservedInstances(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyReservedInstances"),
    MODIFY_ModifySnapshotAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifySnapshotAttribute"),
    MODIFY_ModifySnapshotTier(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifySnapshotTier"),
    MODIFY_ModifySpotFleetRequest(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifySpotFleetRequest"),
    MODIFY_ModifySubnetAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifySubnetAttribute"),
    MODIFY_ModifyTrafficMirrorFilterNetworkServices(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyTrafficMirrorFilterNetworkServices"),
    MODIFY_ModifyTrafficMirrorFilterRule(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyTrafficMirrorFilterRule"),
    MODIFY_ModifyTrafficMirrorSession(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyTrafficMirrorSession"),
    MODIFY_ModifyTransitGateway(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyTransitGateway"),
    MODIFY_ModifyTransitGatewayPrefixListReference(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyTransitGatewayPrefixListReference"),
    MODIFY_ModifyTransitGatewayVpcAttachment(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyTransitGatewayVpcAttachment"),
    MODIFY_ModifyVolume(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVolume"),
    MODIFY_ModifyVolumeAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVolumeAttribute"),
    MODIFY_ModifyVpcAttribute(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpcAttribute"),
    MODIFY_ModifyVpcEndpoint(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpcEndpoint"),
    MODIFY_ModifyVpcEndpointConnectionNotification(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpcEndpointConnectionNotification"),
    MODIFY_ModifyVpcEndpointServiceConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpcEndpointServiceConfiguration"),
    MODIFY_ModifyVpcEndpointServicePayerResponsibility(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpcEndpointServicePayerResponsibility"),
    MODIFY_ModifyVpcEndpointServicePermissions(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpcEndpointServicePermissions"),
    MODIFY_ModifyVpcPeeringConnectionOptions(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpcPeeringConnectionOptions"),
    MODIFY_ModifyVpcTenancy(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpcTenancy"),
    MODIFY_ModifyVpnConnection(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpnConnection"),
    MODIFY_ModifyVpnConnectionOptions(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpnConnectionOptions"),
    MODIFY_ModifyVpnTunnelCertificate(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpnTunnelCertificate"),
    MODIFY_ModifyVpnTunnelOptions(AlertConfHostBitConstant.ACI_UPDATE, "EC2", "ModifyVpnTunnelOptions"),

    DELETE_DeleteCarrierGateway(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteCarrierGateway"),
    DELETE_DeleteClientVpnEndpoint(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteClientVpnEndpoint"),
    DELETE_DeleteClientVpnRoute(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteClientVpnRoute"),
    DELETE_DeleteCoipCidr(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteCoipCidr"),
    DELETE_DeleteCoipPool(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteCoipPool"),
    DELETE_DeleteCustomerGateway(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteCustomerGateway"),
    DELETE_DeleteDhcpOptions(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteDhcpOptions"),
    DELETE_DeleteEgressOnlyInternetGateway(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteEgressOnlyInternetGateway"),
    DELETE_DeleteFleets(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteFleets"),
    DELETE_DeleteFlowLogs(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteFlowLogs"),
    DELETE_DeleteFpgaImage(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteFpgaImage"),
    DELETE_DeleteInstanceEventWindow(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteInstanceEventWindow"),
    DELETE_DeleteInternetGateway(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteInternetGateway"),
    DELETE_DeleteIpam(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteIpam"),
    DELETE_DeleteIpamPool(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteIpamPool"),
    DELETE_DeleteIpamScope(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteIpamScope"),
    DELETE_DeleteKeyPair(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteKeyPair"),
    DELETE_DeleteLaunchTemplate(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteLaunchTemplate"),
    DELETE_DeleteLaunchTemplateVersions(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteLaunchTemplateVersions"),
    DELETE_DeleteLocalGatewayRoute(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteLocalGatewayRoute"),
    DELETE_DeleteLocalGatewayRouteTable(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteLocalGatewayRouteTable"),
    DELETE_DeleteLocalGatewayRouteTableVirtualInterfaceGroupAssociation(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteLocalGatewayRouteTableVirtualInterfaceGroupAssociation"),
    DELETE_DeleteLocalGatewayRouteTableVpcAssociation(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteLocalGatewayRouteTableVpcAssociation"),
    DELETE_DeleteManagedPrefixList(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteManagedPrefixList"),
    DELETE_DeleteNatGateway(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteNatGateway"),
    DELETE_DeleteNetworkInsightsAccessScope(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteNetworkInsightsAccessScope"),
    DELETE_DeleteNetworkInsightsAccessScopeAnalysis(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteNetworkInsightsAccessScopeAnalysis"),
    DELETE_DeleteNetworkInsightsAnalysis(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteNetworkInsightsAnalysis"),
    DELETE_DeleteNetworkInsightsPath(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteNetworkInsightsPath"),
    DELETE_DeleteNetworkInterface(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteNetworkInterface"),
    DELETE_DeleteNetworkInterfacePermission(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteNetworkInterfacePermission"),
    DELETE_DeletePlacementGroup(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeletePlacementGroup"),
    DELETE_DeletePublicIpv4Pool(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeletePublicIpv4Pool"),
    DELETE_DeleteQueuedReservedInstances(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteQueuedReservedInstances"),
    DELETE_DeleteRoute(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteRoute"),
    DELETE_DeleteRouteTable(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteRouteTable"),
    DELETE_DeleteSnapshot(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteSnapshot"),
    DELETE_DeleteSpotDatafeedSubscription(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteSpotDatafeedSubscription"),
    DELETE_DeleteSubnet(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteSubnet"),
    DELETE_DeleteSubnetCidrReservation(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteSubnetCidrReservation"),
    DELETE_DeleteTags(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTags"),
    DELETE_DeleteTrafficMirrorFilter(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTrafficMirrorFilter"),
    DELETE_DeleteTrafficMirrorFilterRule(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTrafficMirrorFilterRule"),
    DELETE_DeleteTrafficMirrorSession(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTrafficMirrorSession"),
    DELETE_DeleteTrafficMirrorTarget(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTrafficMirrorTarget"),
    DELETE_DeleteTransitGateway(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGateway"),
    DELETE_DeleteTransitGatewayConnect(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayConnect"),
    DELETE_DeleteTransitGatewayConnectPeer(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayConnectPeer"),
    DELETE_DeleteTransitGatewayMulticastDomain(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayMulticastDomain"),
    DELETE_DeleteTransitGatewayPeeringAttachment(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayPeeringAttachment"),
    DELETE_DeleteTransitGatewayPolicyTable(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayPolicyTable"),
    DELETE_DeleteTransitGatewayPrefixListReference(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayPrefixListReference"),
    DELETE_DeleteTransitGatewayRoute(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayRoute"),
    DELETE_DeleteTransitGatewayRouteTable(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayRouteTable"),
    DELETE_DeleteTransitGatewayRouteTableAnnouncement(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayRouteTableAnnouncement"),
    DELETE_DeleteTransitGatewayVpcAttachment(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteTransitGatewayVpcAttachment"),
    DELETE_DeleteVolume(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVolume"),
    DELETE_DeleteVpc(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVpc"),
    DELETE_DeleteVpcEndpointConnectionNotifications(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVpcEndpointConnectionNotifications"),
    DELETE_DeleteVpcEndpoints(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVpcEndpoints"),
    DELETE_DeleteVpcEndpointServiceConfigurations(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVpcEndpointServiceConfigurations"),
    DELETE_DeleteVpcPeeringConnection(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVpcPeeringConnection"),
    DELETE_DeleteVpnConnection(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVpnConnection"),
    DELETE_DeleteVpnConnectionRoute(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVpnConnectionRoute"),
    DELETE_DeleteVpnGateway(AlertConfHostBitConstant.ACI_DELETE, "EC2", "DeleteVpnGateway"),

    // EC2 -> SG
    CREATE_CreateSecurityGroup(AlertConfHostBitConstant.ACI_CREATE, "SG", "CreateSecurityGroup"),
    AUTHORIZE_SECURITY_GROUP_INGRESS(AlertConfHostBitConstant.ACI_CREATE,
            "SG", "AuthorizeSecurityGroupIngress"),
    MODIFY_SECURITY_GROUP_RULES(AlertConfHostBitConstant.ACI_UPDATE, "SG", "ModifySecurityGroupRules"),
    REVOKE_SECURITY_GROUP_INGRESS(AlertConfHostBitConstant.ACI_DELETE, "SG","RevokeSecurityGroupIngress"),
    DELETE_DeleteSecurityGroup(AlertConfHostBitConstant.ACI_DELETE, "SG", "DeleteSecurityGroup"),


    // ECR
    CREATE_CreatePullThroughCacheRule(AlertConfHostBitConstant.ACI_CREATE, "ECR", "CreatePullThroughCacheRule"),
    CREATE_CreateRepository(AlertConfHostBitConstant.ACI_CREATE, "ECR", "CreateRepository"),
    PUT_PutImage(AlertConfHostBitConstant.ACI_UPDATE, "ECR", "PutImage"),
    PUT_PutImageScanningConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "ECR", "PutImageScanningConfiguration"),
    PUT_PutImageTagMutability(AlertConfHostBitConstant.ACI_UPDATE, "ECR", "PutImageTagMutability"),
    PUT_PutLifecyclePolicy(AlertConfHostBitConstant.ACI_UPDATE, "ECR", "PutLifecyclePolicy"),
    PUT_PutRegistryPolicy(AlertConfHostBitConstant.ACI_UPDATE, "ECR", "PutRegistryPolicy"),
    PUT_PutRegistryScanningConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "ECR", "PutRegistryScanningConfiguration"),
    PUT_PutReplicationConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "ECR", "PutReplicationConfiguration"),
    DELETE_DeleteLifecyclePolicy(AlertConfHostBitConstant.ACI_DELETE, "ECR", "DeleteLifecyclePolicy"),
    DELETE_DeletePullThroughCacheRule(AlertConfHostBitConstant.ACI_DELETE, "ECR", "DeletePullThroughCacheRule"),
    DELETE_DeleteRegistryPolicy(AlertConfHostBitConstant.ACI_DELETE, "ECR", "DeleteRegistryPolicy"),
    DELETE_DeleteRepository(AlertConfHostBitConstant.ACI_DELETE, "ECR", "DeleteRepository"),
    DELETE_DeleteRepositoryPolicy(AlertConfHostBitConstant.ACI_DELETE, "ECR", "DeleteRepositoryPolicy"),

    // RDS
    CREATE_CreateBlueGreenDeployment(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateBlueGreenDeployment"),
    CREATE_CreateCustomDBEngineVersion(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateCustomDBEngineVersion"),
    CREATE_CreateDBCluster(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBCluster"),
    CREATE_CreateDBClusterEndpoint(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBClusterEndpoint"),
    CREATE_CreateDBClusterParameterGroup(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBClusterParameterGroup"),
    CREATE_CreateDBClusterSnapshot(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBClusterSnapshot"),
    CREATE_CreateDBInstance(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBInstance"),
    CREATE_CreateDBInstanceReadReplica(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBInstanceReadReplica"),
    CREATE_CreateDBParameterGroup(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBParameterGroup"),
    CREATE_CreateDBProxy(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBProxy"),
    CREATE_CreateDBProxyEndpoint(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBProxyEndpoint"),
    CREATE_CreateDBSecurityGroup(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBSecurityGroup"),
    CREATE_CreateDBSnapshot(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBSnapshot"),
    CREATE_CreateDBSubnetGroup(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateDBSubnetGroup"),
    CREATE_CreateEventSubscription(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateEventSubscription"),
    CREATE_CreateGlobalCluster(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateGlobalCluster"),
    CREATE_CreateOptionGroup(AlertConfHostBitConstant.ACI_CREATE, "RDS", "CreateOptionGroup"),

    UPDATE_ModifyActivityStream(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyActivityStream"),
    UPDATE_ModifyCertificates(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyCertificates"),
    UPDATE_ModifyCurrentDBClusterCapacity(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyCurrentDBClusterCapacity"),
    UPDATE_ModifyCustomDBEngineVersion(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyCustomDBEngineVersion"),
    UPDATE_ModifyDBCluster(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBCluster"),
    UPDATE_ModifyDBClusterEndpoint(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBClusterEndpoint"),
    UPDATE_ModifyDBClusterParameterGroup(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBClusterParameterGroup"),
    UPDATE_ModifyDBClusterSnapshotAttribute(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBClusterSnapshotAttribute"),
    UPDATE_ModifyDBInstance(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBInstance"),
    UPDATE_ModifyDBParameterGroup(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBParameterGroup"),
    UPDATE_ModifyDBProxy(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBProxy"),
    UPDATE_ModifyDBProxyEndpoint(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBProxyEndpoint"),
    UPDATE_ModifyDBProxyTargetGroup(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBProxyTargetGroup"),
    UPDATE_ModifyDBSnapshot(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBSnapshot"),
    UPDATE_ModifyDBSnapshotAttribute(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBSnapshotAttribute"),
    UPDATE_ModifyDBSubnetGroup(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyDBSubnetGroup"),
    UPDATE_ModifyEventSubscription(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyEventSubscription"),
    UPDATE_ModifyGlobalCluster(AlertConfHostBitConstant.ACI_UPDATE, "RDS", "ModifyGlobalCluster"),

    DELETE_DeleteBlueGreenDeployment(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteBlueGreenDeployment"),
    DELETE_DeleteCustomDBEngineVersion(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteCustomDBEngineVersion"),
    DELETE_DeleteDBCluster(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBCluster"),
    DELETE_DeleteDBClusterEndpoint(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBClusterEndpoint"),
    DELETE_DeleteDBClusterParameterGroup(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBClusterParameterGroup"),
    DELETE_DeleteDBClusterSnapshot(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBClusterSnapshot"),
    DELETE_DeleteDBInstance(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBInstance"),
    DELETE_DeleteDBInstanceAutomatedBackup(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBInstanceAutomatedBackup"),
    DELETE_DeleteDBParameterGroup(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBParameterGroup"),
    DELETE_DeleteDBProxy(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBProxy"),
    DELETE_DeleteDBProxyEndpoint(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBProxyEndpoint"),
    DELETE_DeleteDBSecurityGroup(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBSecurityGroup"),
    DELETE_DeleteDBSnapshot(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBSnapshot"),
    DELETE_DeleteDBSubnetGroup(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteDBSubnetGroup"),
    DELETE_DeleteEventSubscription(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteEventSubscription"),
    DELETE_DeleteGlobalCluster(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteGlobalCluster"),
    DELETE_DeleteOptionGroup(AlertConfHostBitConstant.ACI_DELETE, "RDS", "DeleteOptionGroup"),

    // S3
    CREATE_CreateBucket(AlertConfHostBitConstant.ACI_CREATE, "S3", "CreateBucket"),
    CREATE_CreateMultipartUpload(AlertConfHostBitConstant.ACI_CREATE, "S3", "CreateMultipartUpload"),

    PUT_PutBucketAccelerateConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketAccelerateConfiguration"),
    PUT_PutBucketAcl(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketAcl"),
    PUT_PutBucketAnalyticsConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketAnalyticsConfiguration"),
    PUT_PutBucketCors(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketCors"),
    PUT_PutBucketEncryption(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketEncryption"),
    PUT_PutBucketIntelligentTieringConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketIntelligentTieringConfiguration"),
    PUT_PutBucketInventoryConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketInventoryConfiguration"),
    PUT_PutBucketLifecycle(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketLifecycle"),
    PUT_PutBucketLifecycleConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketLifecycleConfiguration"),
    PUT_PutBucketLogging(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketLogging"),
    PUT_PutBucketMetricsConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketMetricsConfiguration"),
    PUT_PutBucketNotification(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketNotification"),
    PUT_PutBucketNotificationConfiguration(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketNotificationConfiguration"),
    PUT_PutBucketOwnershipControls(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketOwnershipControls"),
    PUT_PutBucketPolicy(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketPolicy"),
    PUT_PutBucketReplication(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketReplication"),
    PUT_PutBucketRequestPayment(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketRequestPayment"),
    PUT_PutBucketTagging(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketTagging"),
    PUT_PutBucketVersioning(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketVersioning"),
    PUT_PutBucketWebsite(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutBucketWebsite"),
    PUT_PutObject(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutObject"),
    PUT_PutObjectAcl(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutObjectAcl"),
    PUT_PutObjectLegalHold(AlertConfHostBitConstant.ACI_UPDATE, "S3", "PutObjectLegalHold"),

    DELETE_DeleteBucket(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucket"),
    DELETE_DeleteBucketAnalyticsConfiguration(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketAnalyticsConfiguration"),
    DELETE_DeleteBucketCors(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketCors"),
    DELETE_DeleteBucketEncryption(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketEncryption"),
    DELETE_DeleteBucketIntelligentTieringConfiguration(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketIntelligentTieringConfiguration"),
    DELETE_DeleteBucketInventoryConfiguration(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketInventoryConfiguration"),
    DELETE_DeleteBucketLifecycle(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketLifecycle"),
    DELETE_DeleteBucketMetricsConfiguration(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketMetricsConfiguration"),
    DELETE_DeleteBucketOwnershipControls(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketOwnershipControls"),
    DELETE_DeleteBucketPolicy(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketPolicy"),
    DELETE_DeleteBucketReplication(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketReplication"),
    DELETE_DeleteBucketTagging(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketTagging"),
    DELETE_DeleteBucketWebsite(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteBucketWebsite"),
    DELETE_DeleteObject(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteObject"),
    DELETE_DeleteObjects(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteObjects"),
    DELETE_DeleteObjectTagging(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeleteObjectTagging"),
    DELETE_DeletePublicAccessBlock(AlertConfHostBitConstant.ACI_DELETE, "S3", "DeletePublicAccessBlock"),


    // VPC NETWORK ACL ( VPC 는 UPDATE 가 없다. )
    CREATE_CreateNetworkAcl(AlertConfHostBitConstant.ACI_CREATE, "VPC", "CreateNetworkAcl"),
    CREATE_NETWORK_ACL_ENTRY(AlertConfHostBitConstant.ACI_CREATE, "VPC", "CreateNetworkAclEntry"),
    DELETE_DeleteNetworkAcl(AlertConfHostBitConstant.ACI_DELETE, "VPC", "DeleteNetworkAcl"),
    DELETE_NETWORK_ACL_ENTRY(AlertConfHostBitConstant.ACI_DELETE, "VPC", "DeleteNetworkAclEntry"),

    ;

    public final int code;
    public final String source;
    public final String value;

    EventNameEnum(int code, String source, String value) {
        this.code = code;
        this.source = source;
        this.value = value;
    }

    public String eventName() {
        return this.value;
    }

    public static Optional<EventNameEnum> getEventNameBySource(int code, String source) {
        return Arrays.stream(EventNameEnum.values())
                .filter(nameEnum -> nameEnum.code == code)
                .filter(nameEnum -> nameEnum.source.equals(source))
                .findFirst();
    }

    public static Optional<EventNameEnum> getEventNameByValue(int code, String value) {
        return Arrays.stream(EventNameEnum.values())
                .filter(nameEnum -> nameEnum.code == code)
                .filter(nameEnum -> nameEnum.value.equals(value))
                .findFirst();
    }
}
